//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// -----------------------------------------------------------------------------
//<auto-generated>
//   该文件由 AutoGenerateABPackage.CreateAssetNameClass 方法生成
//   记录了储存在AB包内的资源名称
//   具有记忆变量名修改的功能，可以修改文件的变量名称
//</auto-generated>
//------------------------------------------------------------------------------
namespace Core.AssetLoader {
    
    
    public class AssetPath {
        
        public class Icon {
            
            public const string DefaultProfilePhoto = "Icon/DefaultProfilePhoto";
            
            public const string ProcessBar = "Icon/ProcessBar";
            
            public const string RoundedRectangle = "Icon/RoundedRectangle";
            
            public class OperationResult {
                
                public const string Error = "Icon/OperationResult/Error";
                
                public const string Successful = "Icon/OperationResult/Successful";
                
                public const string Warring = "Icon/OperationResult/Warring";
            }
            
            public class SignalStrength {
                
                public const string Bad = "Icon/SignalStrength/Bad";
                
                public const string Good = "Icon/SignalStrength/Good";
                
                public const string Middle = "Icon/SignalStrength/Middle";
            }
        }
        
        public class Prefab {
            
            public const string Player = "Prefab/Player";
            
            public const string PlayerVisual = "Prefab/PlayerVisual";
            
            public class UI {
                
                public const string Canvas = "Prefab/UI/Canvas";
                
                public const string Chat = "Prefab/UI/Chat";
                
                public const string DisplayPlayerBox = "Prefab/UI/DisplayPlayerBox";
                
                public const string DisplayRoomBox = "Prefab/UI/DisplayRoomBox";
                
                public const string Login = "Prefab/UI/Login";
                
                public const string MessageTip = "Prefab/UI/MessageTip";
                
                public const string Register = "Prefab/UI/Register";
                
                public const string Room = "Prefab/UI/Room";
                
                public const string RoomHall = "Prefab/UI/RoomHall";
                
                public const string SceneLoading = "Prefab/UI/SceneLoading";
            }
        }
    }
}
