// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RequestResult.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network.Protocol {

  /// <summary>Holder for reflection information generated from RequestResult.proto</summary>
  public static partial class RequestResultReflection {

    #region Descriptor
    /// <summary>File descriptor for RequestResult.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestResultReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNSZXF1ZXN0UmVzdWx0LnByb3RvEhBOZXR3b3JrLlByb3RvY29sGhlnb29n",
            "bGUvcHJvdG9idWYvYW55LnByb3RvIpABCg1SZXF1ZXN0UmVzdWx0EjAKCmFj",
            "dGlvbkNvZGUYASABKA4yHC5OZXR3b3JrLlByb3RvY29sLkFjdGlvbkNvZGUS",
            "FAoMaXNTdWNjZXNzZnVsGAIgASgIEhMKC2luZm9ybWF0aW9uGAMgASgJEiIK",
            "BGFyZ3MYBCABKAsyFC5nb29nbGUucHJvdG9idWYuQW55KoMCCgpBY3Rpb25D",
            "b2RlEggKBE5vbmUQABIMCghSZWdpc3RlchABEgkKBUxvZ2luEAISEAoMQ3Jl",
            "YXRlUGxheWVyEAMSDgoKQ3JlYXRlUm9vbRAEEgwKCEpvaW5Sb29tEAUSDAoI",
            "RXhpdFJvb20QBhIMCghSb29tTGlzdBAHEgwKCFJvb21JbmZvEAgSCAoEQ2hh",
            "dBAJEg8KC1N0YXJ0UmVhZGx5EAoSDQoJR2FtZVN0YXJ0EAsSEAoMUG9zaXRp",
            "b25TeW5jEAwSDQoJUXVpdGVHYW1lEA0SCgoGQXR0YWNrEA4SDgoKU2VhcmNo",
            "Um9vbRAPEhEKDVF1ZXJ5VXNlckluZm8QEGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Network.Protocol.ActionCode), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Protocol.RequestResult), global::Network.Protocol.RequestResult.Parser, new[]{ "ActionCode", "IsSuccessful", "Information", "Args" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ActionCode {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Register")] Register = 1,
    [pbr::OriginalName("Login")] Login = 2,
    [pbr::OriginalName("CreatePlayer")] CreatePlayer = 3,
    [pbr::OriginalName("CreateRoom")] CreateRoom = 4,
    [pbr::OriginalName("JoinRoom")] JoinRoom = 5,
    [pbr::OriginalName("ExitRoom")] ExitRoom = 6,
    [pbr::OriginalName("RoomList")] RoomList = 7,
    [pbr::OriginalName("RoomInfo")] RoomInfo = 8,
    [pbr::OriginalName("Chat")] Chat = 9,
    [pbr::OriginalName("StartReadly")] StartReadly = 10,
    [pbr::OriginalName("GameStart")] GameStart = 11,
    [pbr::OriginalName("PositionSync")] PositionSync = 12,
    [pbr::OriginalName("QuiteGame")] QuiteGame = 13,
    [pbr::OriginalName("Attack")] Attack = 14,
    [pbr::OriginalName("SearchRoom")] SearchRoom = 15,
    [pbr::OriginalName("QueryUserInfo")] QueryUserInfo = 16,
  }

  #endregion

  #region Messages
  public sealed partial class RequestResult : pb::IMessage<RequestResult> {
    private static readonly pb::MessageParser<RequestResult> _parser = new pb::MessageParser<RequestResult>(() => new RequestResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Protocol.RequestResultReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestResult(RequestResult other) : this() {
      actionCode_ = other.actionCode_;
      isSuccessful_ = other.isSuccessful_;
      information_ = other.information_;
      args_ = other.args_ != null ? other.args_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestResult Clone() {
      return new RequestResult(this);
    }

    /// <summary>Field number for the "actionCode" field.</summary>
    public const int ActionCodeFieldNumber = 1;
    private global::Network.Protocol.ActionCode actionCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Network.Protocol.ActionCode ActionCode {
      get { return actionCode_; }
      set {
        actionCode_ = value;
      }
    }

    /// <summary>Field number for the "isSuccessful" field.</summary>
    public const int IsSuccessfulFieldNumber = 2;
    private bool isSuccessful_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsSuccessful {
      get { return isSuccessful_; }
      set {
        isSuccessful_ = value;
      }
    }

    /// <summary>Field number for the "information" field.</summary>
    public const int InformationFieldNumber = 3;
    private string information_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Information {
      get { return information_; }
      set {
        information_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "args" field.</summary>
    public const int ArgsFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Any args_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any Args {
      get { return args_; }
      set {
        args_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionCode != other.ActionCode) return false;
      if (IsSuccessful != other.IsSuccessful) return false;
      if (Information != other.Information) return false;
      if (!object.Equals(Args, other.Args)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionCode != 0) hash ^= ActionCode.GetHashCode();
      if (IsSuccessful != false) hash ^= IsSuccessful.GetHashCode();
      if (Information.Length != 0) hash ^= Information.GetHashCode();
      if (args_ != null) hash ^= Args.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ActionCode != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionCode);
      }
      if (IsSuccessful != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsSuccessful);
      }
      if (Information.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Information);
      }
      if (args_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Args);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActionCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionCode);
      }
      if (IsSuccessful != false) {
        size += 1 + 1;
      }
      if (Information.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Information);
      }
      if (args_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Args);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestResult other) {
      if (other == null) {
        return;
      }
      if (other.ActionCode != 0) {
        ActionCode = other.ActionCode;
      }
      if (other.IsSuccessful != false) {
        IsSuccessful = other.IsSuccessful;
      }
      if (other.Information.Length != 0) {
        Information = other.Information;
      }
      if (other.args_ != null) {
        if (args_ == null) {
          Args = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Args.MergeFrom(other.Args);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionCode = (global::Network.Protocol.ActionCode) input.ReadEnum();
            break;
          }
          case 16: {
            IsSuccessful = input.ReadBool();
            break;
          }
          case 26: {
            Information = input.ReadString();
            break;
          }
          case 34: {
            if (args_ == null) {
              Args = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Args);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
