// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SendChatRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network.Protocol {

  /// <summary>Holder for reflection information generated from SendChatRequest.proto</summary>
  public static partial class SendChatRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for SendChatRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SendChatRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVTZW5kQ2hhdFJlcXVlc3QucHJvdG8SEE5ldHdvcmsuUHJvdG9jb2wiSwoP",
            "U2VuZENoYXRSZXF1ZXN0EhMKC3JlcXVlc3RlcklEGAEgASgFEg4KBnJvb21J",
            "RBgCIAEoBRITCgtjaGF0Q29udGVudBgDIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Protocol.SendChatRequest), global::Network.Protocol.SendChatRequest.Parser, new[]{ "RequesterID", "RoomID", "ChatContent" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SendChatRequest : pb::IMessage<SendChatRequest> {
    private static readonly pb::MessageParser<SendChatRequest> _parser = new pb::MessageParser<SendChatRequest>(() => new SendChatRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SendChatRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Protocol.SendChatRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendChatRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendChatRequest(SendChatRequest other) : this() {
      requesterID_ = other.requesterID_;
      roomID_ = other.roomID_;
      chatContent_ = other.chatContent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendChatRequest Clone() {
      return new SendChatRequest(this);
    }

    /// <summary>Field number for the "requesterID" field.</summary>
    public const int RequesterIDFieldNumber = 1;
    private int requesterID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RequesterID {
      get { return requesterID_; }
      set {
        requesterID_ = value;
      }
    }

    /// <summary>Field number for the "roomID" field.</summary>
    public const int RoomIDFieldNumber = 2;
    private int roomID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RoomID {
      get { return roomID_; }
      set {
        roomID_ = value;
      }
    }

    /// <summary>Field number for the "chatContent" field.</summary>
    public const int ChatContentFieldNumber = 3;
    private string chatContent_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ChatContent {
      get { return chatContent_; }
      set {
        chatContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SendChatRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SendChatRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequesterID != other.RequesterID) return false;
      if (RoomID != other.RoomID) return false;
      if (ChatContent != other.ChatContent) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequesterID != 0) hash ^= RequesterID.GetHashCode();
      if (RoomID != 0) hash ^= RoomID.GetHashCode();
      if (ChatContent.Length != 0) hash ^= ChatContent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequesterID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequesterID);
      }
      if (RoomID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomID);
      }
      if (ChatContent.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ChatContent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequesterID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequesterID);
      }
      if (RoomID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomID);
      }
      if (ChatContent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatContent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SendChatRequest other) {
      if (other == null) {
        return;
      }
      if (other.RequesterID != 0) {
        RequesterID = other.RequesterID;
      }
      if (other.RoomID != 0) {
        RoomID = other.RoomID;
      }
      if (other.ChatContent.Length != 0) {
        ChatContent = other.ChatContent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequesterID = input.ReadInt32();
            break;
          }
          case 16: {
            RoomID = input.ReadInt32();
            break;
          }
          case 26: {
            ChatContent = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
